#!/usr/bin/env bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "$DIR/venv/bin/activate"

exec "$DIR/venv/bin/python" "$DIR/anaconda_server/jsonserver.py" -p test 9999 DEBUG
